APPLICATION_NAME: str = "soundbyte"

DEFAULT_CHANNELS: int = 2
DEFAULT_SAMPLE_WIDTH: int = 2  # CD Quality
DEFAULT_SEPARATOR: str = '-'

LOADER_BASE_FILE_NAME: str = f"{APPLICATION_NAME}.media.download"
METADATA_FILE_TYPE: str = "info.json"
AUDIO_FILE_TYPE: str = "wav"

WORK_ROOT: str = f"C:\\Users\\John Hart\\Desktop\\{APPLICATION_NAME}"
TEMP_ROOT: str = f"{WORK_ROOT}\\temp"
CACHE_ROOT: str = f"{WORK_ROOT}\\cache"
EXPORT_ROOT: str = f"{WORK_ROOT}\\export"

LOG_DEBUG: bool = True
LOG_WARNING: bool = True
LOG_ERROR: bool = True
LOG_TO_CONSOLE: bool = True

LOG_ROOT: str = f"{WORK_ROOT}\\log"
LOG_FILE_TYPE: str = "log"
LOG_FILE_NAME: str = f"{LOG_ROOT}\\{APPLICATION_NAME}.{LOG_FILE_TYPE}"

DEFAULT_DOWNLOADER_MODULE: str = "aria2c"
DEFAULT_FRAME_RATE: int = 44100

DEFAULT_CLIPS: int = 10
DEFAULT_DETECTION_WINDOW_MILISECONDS: int = 10
DEFAULT_LOW_THRESHOLD: float = -20.0
DEFAULT_DRIFT_DECIBELS: float = 0.1
DEFAULT_CLIP_SIZE_MILISECONDS: int = 9000
DEFAULT_BEAT_COUNT: int = 4
DEFAULT_ATTACK_MILISECONDS: int = 50
DEFAULT_DECAY_MILISECONDS: int = 50
DEFAULT_PAD_DURATION_MILISECONDS: int = 250

DEFAULT_FADE_IN_MILISECONDS: int = 500
DEFAULT_FADE_OUT_MILISECONDS: int = 500

MAXIMUM_CLIP_SIZE_MILISECONDS: int = 27000
MAXIMUM_SAMPLES: int = 24 * 60 * 60 * DEFAULT_FRAME_RATE
