DEFAULT_DURATION = 3
DEFAULT_THRESHOLD = 0.01
DEFAULT_SAMPLE_RATE = 44100
DEFAULT_CLIP_LIMIT = 10
DEFAULT_FADE_IN_DURATION = 500
DEFAULT_FADE_OUT_DURATION = 500

DEFAULT_FILE_NAME = 'media.download'

METADATA_FILE_TYPE = 'info.json'
LOG_FILE_TYPE = 'log'
AUDIO_FILE_TYPE = 'wav'

WORK_ROOT = 'C:\\Users\\John Hart\\Desktop\\audiobot'
CACHE_ROOT = WORK_ROOT + '\\cache'
LOG_ROOT = WORK_ROOT + '\\log'
EXPORT_ROOT = WORK_ROOT + '\\export'

LOG_DEBUG = True
LOG_WARNING = True
LOG_ERROR = True
LOG_TO_CONSOLE = True

LOG_FILE_NAME = LOG_ROOT + '\\application.log'

DEFAULT_EXTERNAL_DOWNLOADER = 'aria2c'
